[tool.black]
line-length = 79
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
    /(
        \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
        | venv
    )/
'''

[tool.ruff]
line-length = 79
exclude = [
    "**/__init__.py",
]

